name: daydart
description: With the same Day. JS API time processing library, convenient to do DateTime operation..
repository: https://github.com/csjiabin/daydart
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
